export const products = [
  {
    id: 1,
    name: "Asafoetida Powder",
    image_url: "/assets/asafoetida-powder.png",
    discount_price: 60.0,
    mrp: 80.0,
    quantity: "50g",
    weight: 50.0,
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Millet Instant Mix",
    image_url: "/assets/millets-powder.png",
    discount_price: 90.0,
    mrp: 100.0,
    quantity: "75g",
    weight: 75.0,
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Turmeric Powder",
    image_url: "/assets/turmericPowder.jpg",
    discount_price: 40.0,
    mrp: 50.0,
    quantity: "100g",
    weight: 100.0,
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Ginger Powder",
    image_url: "/assets/gingerPowder.webp",
    discount_price: 55.0,
    mrp: 70.0,
    quantity: "75g",
    weight: 75.0,
    available: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Chilli Powder",
    image_url: "/assets/chilliPowder.webp",
    discount_price: 45.0,
    mrp: 55.0,
    quantity: "50g",
    weight: 50.0,
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Cumin Powder",
    image_url: "/assets/cuminPowder.jpg",
    discount_price: 80.0,
    mrp: 100.0,
    quantity: "100g",
    weight: 100.0,
    available: true,
    created_at: new Date().toISOString(),
  },
  // Additional products can be added here...
];
